version: "3.8"

services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile-AnalyticsService
    container_name: analytics-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    driver: bridge
    name: internal
    external: true