version: "3.8"

services:
  billing-service:
    build:
      context: .
      dockerfile: DockerFile-BillingService
    container_name: billing-service
    ports:
      - "8081:8081"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    name: internal
    external: true
