version: "3.8"

services:
  auth-mysql-db:
    image: mysql
    container_name: auth-mysql-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: auth-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-volumes:/var/lib/mysql
    networks:
      - internal

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-AuthService
    container_name: auth-service
    ## As requests are handled via api; so not exposing this port outside
#    ports:
#      - "8085:8085"
    env_file:
      - .env
    depends_on:
      - auth-mysql-db
    networks:
      - internal

volumes:
  mysql-volumes:
networks:
  internal:
    driver: bridge
    name: internal
    external: true